# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

toggle_key: OFF

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Phrases
  - trigger: ";imo"
    replace: "in my opinion"

  - trigger: ";hu"
    replace: "have you"

  - trigger: ";asap"
    replace: "as soon as possible"

  - trigger: ";btw"
    replace: "by the way"

  - trigger: ";fwis"
    replace: "from what I see"

  - trigger: ";ofc"
    replace: "of course"

  # Words
  - trigger: ";def"
    replace: "definitely"

  - trigger: ";gql"
    replace: "GraphQL"

  # Code
  - trigger: ";mdc"
    replace: "```\n\n```"

  # Dates
  - trigger: ";date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%d/%m/%Y"

  # Zettelkasten
  - trigger: ";zid"
    replace: "§{{mydate}} - "
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y%m%d%H%M"

  # Personal info
  - trigger: ";name"
    replace: "Nikita"

  - trigger: ";sname"
    replace: "Tchayka"

  - trigger: ";fsname"
    replace: "Tchayka Razumov"

  - trigger: ";fname"
    replace: "Nikita Tchayka Razumov"

  - trigger: ";email"
    replace: "nikitatchayka@outlook.com"

  - trigger: ";wemail"
    replace: "nick@booster.cloud"

  - trigger: ";address"
    replace: "Calle Tamara 13"

  # Shell commands
  - trigger: ";shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"

  - trigger: ";shrug"
    replace: "¯\\_(ツ)_/¯"

  - trigger: ";tableflip"
    replace: "(╯°□°）╯︵ ┻━┻"

  - trigger: ";lenny"
    replace: "( ͡° ͜ʖ ͡°)"
